mongodb:
  image: tutum/mongodb:3.0
  environment:
    - OPLOG_SIZE=1
    - MONGODB_PASS=test
  ports:
    - "27018:27017"
    - "28018:28017"
elasticsearch:
    image: tutum/elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTICSEARCH_USER=admin
      - ELASTICSEARCH_PASS=test
#crawler:
#  image: 'tutum.co/maximeheckel/stackfiles-crawler:staging'
#  environment:
#    - BASE_URL=http://localhost:4000
#    - MONGODB_PASS=test
#    - SCHEDULE_TIME=0
#  links:
#    - mongodb
